export const healthKeywords = [
  'Hello',
  'Hi',
  'Pregnancy',
  'Ovulatory disorders (e.g., PCOS)',
  'Diminished ovarian reserve',
  'Fallopian tube blockage or damage',
  'Uterine abnormalities (e.g., fibroids, polyps)',
  'Endometriosis',
  'Hormonal imbalances',
  'Premature ovarian failure',
  'Thyroid disorders affecting fertility',
  'Autoimmune conditions affecting fertility',
  'Hyperprolactinemia',
  'Anovulation',
  'Luteal phase defects',
  "Asherman's syndrome (uterine adhesions)",
  'Cervical factors (e.g., hostile cervical mucus)',
  'Obesity-related infertility',
  'Age-related infertility',
  'Genetic factors affecting fertility',
  'Unexplained infertility',
  'Pelvic inflammatory disease (PID)',
  'Ovulation tracking and basal body temperature charting',
  'Hormone level testing (LH, FSH, estradiol, progesterone)',
  'Transvaginal ultrasound',
  'Hysterosalpingography (HSG)',
  'Laparoscopy',
  'Ovarian reserve testing (AMH, FSH)',
  'Thyroid function tests',
  'Prolactin level testing',
  'Genetic testing (karyotype analysis)',
  'Anti-Müllerian hormone (AMH) testing',
  'Hysteroscopy',
  'Endometrial biopsy',
  'Sonohysterography',
  'Cervical mucus analysis',
  'Ovarian follicle tracking',
  'Fallopian tube patency tests (dye test, hysterosalpingo-contrast sonography)',
  'Anti-nuclear antibody (ANA) testing',
  'Pelvic ultrasound',
  'Serum progesterone levels during the luteal phase',
  'Immunological tests (e.g., antiphospholipid antibodies)',
  'Environmental factors affecting fertility',
  'In vitro gametogenesis (IVG)',
  'Ovarian tissue cryopreservation and transplantation',
  'Uterine transplantation',
  'Artificial gametes',
  'Three-parent IVF (Mitochondrial replacement therapy)',
  'Ovarian rejuvenation',
  'Natural cycle IVF',
  'Intracytoplasmic morphologically selected sperm injection (IMSI)',
  'Time-lapse embryo imaging',
  'Preimplantation genetic testing for aneuploidy (PGT-A)',
  'EmbryoScope technology',
  'Cryopreservation of eggs, embryos, and ovarian tissue',
  'Egg vitrification',
  'Embryo vitrification',
  'Blastocyst culture and transfer',
  'Single embryo transfer',
  'Embryo glue (endometrial receptivity)',
  'Embryo genetic testing (PGT-M and PGT-SR)',
  'Ovarian stimulation protocols (short vs. long protocols)',
  'Low sperm count (oligospermia)',
  'Poor sperm motility (asthenospermia)',
  'Abnormal sperm morphology (teratospermia)',
  'Erectile dysfunction',
  'Varicocele',
  'Obstructive azoospermia',
  'Non-obstructive azoospermia',
  'Semen analysis',
  'Sperm count assessment',
  'Sperm motility analysis',
  'Sperm morphology evaluation',
  'Hormone level testing (FSH, LH, testosterone)',
  'Testicular ultrasound',
  'Testicular biopsy',
  'Post-ejaculation urine analysis',
  'Antisperm antibody testing',
  'Scrotal Doppler ultrasound',
  'Transrectal ultrasound',
  'Karyotype analysis',
  'Endocrine evaluation',
  'Physical examination',
  'Testicular trauma',
  'Chromosomal abnormalities',
  'Retrograde ejaculation',
  'Hypospadias',
  'Undescended testicles (cryptorchidism)',
  'Pregnancies',
  'Abortions',
  'ART (Assisted Reproductive Technologies)',
  'IVF (In vitro fertilization)',
  'ICSI (Intracytoplasmic Sperm Injection)',
  'Egg freezing',
  'Sperm donation',
  'Egg donation',
  'LGBTQ+ family',
  'Genetic screening',
  'Embryo grading',
  'IVF success rates',
  'Surrogate motherhood',
  'fertility',
  'treatment',
  'reproductive',
  'infertility',
  'semen',
  'test',
];
